---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "remove dependancies that are no longer required"
  become: yes
  apt:
    autoremove: yes
  
- name: "install npm & dependancies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "creates directory"
  file:
    name: ~/web
    state: directory

- name: "copy files"
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: "run server"
  shell: |
    pm2 start ~/web/index.js -f
    

